### PR TITLE
Add Nicaragua flag

### PR DESCRIPTION
**Pull request by brunocavalcantelima**
Add new flag: Nicaragua

print bandeiras

### CODE REVIEW

**Comment by norkans7** [comment]
@brunocavalcantelima you need to make sure to add a favico as well in https://github.com/rapidpro/ureport/tree/main/static/img/favicos

**Review by norkans7 — CHANGES_REQUESTED** [review]
needs favico

**Comment by brunocavalcantelima** [comment]
@norkans7 , we did the changes you asked. Added favicon to Nicaragua's Ureport.

**Review by norkans7 — APPROVED** [review]

**Comment by matmsa27** [comment]
Hi @norkans7 , could you merge this PR pls? And then we can update our instance here, I appreciate this, thanks.

**Pull request merged**
