### PR TITLE
Add flag to exclude fonts

### PR DESCRIPTION
**Pull request by norkans7**

### CODE REVIEW

**Comment by nicpottier** [comment]
Would it make more sense to have a setting to let an org pick the font? this seems very specific without adding much flexibility

**Comment by norkans7** [comment]
like a dropdown?

**Comment by nicpottier** [comment]
I don't think we need a drop down, could just be the font declaration, basically inserting the styles. That would let them use whatever font they want and would override the default ones.

**Comment by norkans7** [comment]
replaced by https://github.com/rapidpro/ureport/pull/317

**Pull request closed without merging**
