### PR TITLE
Add Uniendo Voces Flags

### PR DESCRIPTION
**Pull request by matmsa27**

### CODE REVIEW

**Review by norkans7 — CHANGES_REQUESTED** [review]
In addition to add `countries_codes` you need to make sure each site has at least an opinion and a story displayed 

also remove `static/img/flags` that is no longer used

**Comment by matmsa27** [comment]
Hi @norkans7, I updated this PR with new standards. About Bolivia workspace, is a workspace working and configured on Rapidpro, have contacts and flows running for UReporters. I will talk with the customer to publish information on UReport.

**Comment by norkans7** [comment]
screenshot of flags?

Also a published poll is required really, do you want to make a different PR for the Bolivia site then?

**Comment by matmsa27** [comment]
image

We are publishing a poll for Bolivia UReport. When is available I will update you here.

**Comment by matmsa27** [comment]
Hi @norkans7 , poll and story are published on UReport Uniendo Voices Bolivia.

**Comment by norkans7** [comment]
You probably need to make the poll featured so it appears on the home page.

**Pull request merged**
