### PR TITLE
Add Madagascar flag

### PR DESCRIPTION
**Pull request by evansmurithi**

### CODE REVIEW

**Comment by norkans7** [comment]
@evansmurithi please share a screenshot of the URL /icons_display/ to see the icon has the correct dimensions

**Comment by evansmurithi** [comment]
@norkans7 unfortunately the version running on madagascar.ureport.in doesn't have that url

**Comment by norkans7** [comment]
You can have the screenshot form the dev environment

**Comment by evansmurithi** [comment]
@norkans7 here's the screenshot with the highlighted country flag
ureport-rivers-onalabs-org-icons_display-

**Comment by norkans7** [comment]
I think the icon is does not have the correct size there and also it should be sorted alphabetically by country name.
You should not highlight as this is the test to make sure the file has the proper size

You probably need to reach out to the CO or the design team for the correct icon to use there as you see all the others have the same size

**Comment by evansmurithi** [comment]
@norkans7 noted

**Comment by evansmurithi** [comment]
@norkans7 find updated screenshot below:
ureport-rivers-onalabs-org-icons_display-

**Comment by norkans7** [comment]
Looks goods @evansmurithi

**Pull request merged**
