### PR TITLE
Add sync schedule on opinions admin list

### PR DESCRIPTION
**Pull request by norkans7**

### CODE REVIEW

**Comment by norkans7** [comment]
U-Report 2020-07-31 14-37-46

I changed the table to have room for one more column

**Comment by norkans7** [comment]
I think that is the first step and not allowing to manually resync yet

**Comment by norkans7** [comment]
BEFORE opinions table
U-Report 2020-07-31 15-39-28

**Comment by nicpottier** [comment]
Looks like a reasonable first step, should probably use plural translation to get rid of awkward `is/are`

**Pull request merged**
