### PR TITLE
Dedupe poll response categories

### PR DESCRIPTION
**Pull request by norkans7**

### CODE REVIEW

**Comment by nicpottier** [comment]
`PollResponseCategory` just maps to actual categories on RapidPro flows ya? Any reason we aren't just calling the API and going from there?

**Comment by norkans7** [comment]
We currently allow admin to customize how the category will be displayed as.
The poll is added we call the RapidPro flows API to get the definition and parse that to create the possible questions and categories for each.

**Comment by norkans7** [comment]
@nicpottier something else I am missing?

**Comment by nicpottier** [comment]
Sorry, what is this deduping then?

**Comment by norkans7** [comment]
question response categories, they use to have a rule_uuid and on RapidPro the category could be added twice such as "Other" now we want those to be unique and we no longer have the field rule_uuid from RapidPro so we will remove that as well

**Comment by nicpottier** [comment]
Ok ok.

**Review by nicpottier — APPROVED** [review]

**Pull request merged**
