### PR TITLE
Limit the creation of polls to 1 per flow in 5 minutes

### PR DESCRIPTION
**Pull request by norkans7**

### CODE REVIEW

**Comment by nicpottier** [comment]
Does Poll have an active field?

**Comment by norkans7** [comment]
Yes

**Comment by teehamaral** [comment]
Is there a reason for that? Just to know :)

**Comment by norkans7** [comment]
@teehamaral we have notice some users on slow internet connection creating duplicated polls
and one without questions, this will prevent that

**Pull request merged**
