### PR TITLE
Add Kenya flag

### PR DESCRIPTION
**Pull request by Sandro-Meireles**

### CODE REVIEW

**Review by norkans7 — CHANGES_REQUESTED** [review]
icon looks wrong, Y instead of U

**Comment by matmsa27** [comment]
Hi @norkans7 , on UReport Kenya, the customers will use a new name, `Yunitok`, for this they want to change the icon like Croatia changed the icon for Z.

**Comment by norkans7** [comment]
Ohhh I did not notice that one either
Are those icons from the design team?
Or the CO came up with them?

**Comment by matmsa27** [comment]
The flag was developed by the U-Report global team by Hira Hafeez Ur Rehman in coordination with the designer.

**Comment by norkans7** [comment]
Thanks to clarify

**Review by norkans7 — APPROVED** [review]

**Comment by matmsa27** [comment]
Thanks, @norkans7, can you merge this PR?

**Pull request merged**
