### PR TITLE
Update arabic language

### PR DESCRIPTION
**Pull request by teehamaral**
This PR includes the Arabic translation updated (94%).

### CODE REVIEW

**Comment by norkans7** [comment]
where are these maintained from? are they in sync with Transifex?

**Comment by teehamaral** [comment]
Yes. They were translated in the Transifex.

**Comment by norkans7** [comment]
It seems to be different from https://www.transifex.com/rapidpro/ureport/ 
do you use a different transifex project?

**Comment by nelsonlapf** [comment]
Hi norkans7,

It´s the same project, could you tell me what´s different?

**Comment by norkans7** [comment]
@nelsonlapf @teehamaral  these changes are removing the word "U-REPORT" and I still see it on the transifex translations.
Really I think it is a good practice to translate first and review the translations on Transifex then pull them in the repo

**Comment by nelsonlapf** [comment]
Hi @norkans7 We are analysing it with the guy who did the translation.

**Comment by nelsonlapf** [comment]
The guy who was translating to Arabic was translating directly in the file instead of using the Transifex. We asked him to translated from there (Transifex). When he have finished we will do another PR. Sorry for the wrong information above.

**Comment by norkans7** [comment]
Alright @nelsonlapf

**Comment by teehamaral** [comment]
We realized that is missing translate a string already translated before, wait a moment, please, before merge, we are fixing.

**Comment by norkans7** [comment]
I think this still has issues, I see repeated strings, I guess you had fix git conflicts.

I think it is better to just pull the latest file from transifex and add it.

I think a different PR might be easier.

**Comment by teehamaral** [comment]
Ok.

**Pull request closed without merging**
