### PR TITLE
Gin index

### PR DESCRIPTION
**Pull request by norkans7**
This will address https://sentry.io/nyaruka/ureport/issues/532862273 

I'll do more experiments to make sure this does not degrade the current performance

### CODE REVIEW

**Comment by norkans7** [comment]
@nicpottier experimented with the index locally the poll result will be saved correctly

**Comment by norkans7** [comment]
the other option to solve this is to keep the existing index and just limit the text to shorter that 2560 for example

**Comment by nicpottier** [comment]
Oh these are for word clouds huh? Ya, we should just trim those to something more reasonable as a first go.

**Comment by norkans7** [comment]
Will do the trim on another branch

**Pull request closed without merging**
