### PR TITLE
Added Macedonian language

### PR DESCRIPTION
**Pull request by Sandro-Meireles**

### CODE REVIEW

**Comment by matmsa27** [comment]
Hi @norkans7 , can you help us with this PR?

**Comment by norkans7** [comment]
Looks good

**Comment by matmsa27** [comment]
Thank you @norkans7

**Comment by norkans7** [comment]
You also need to look again into https://github.com/rapidpro/ureport/pull/678

**Comment by matmsa27** [comment]
Sure, we await the new image with the correct pattern from our designer to update the PR.

**Pull request merged**
