### PR TITLE
Fix/editor unordered list

### PR DESCRIPTION
**Pull request by WilliamTales**
This fixes the CSS behavior that hides the marks outside visible edit area.

### CODE REVIEW

**Comment by johncordeiro** [comment]
@nicpottier @norkans7 any thoughts on that?

**Comment by norkans7** [comment]
can you add a screenshot?

**Comment by norkans7** [comment]
@WilliamTales @johncordeiro

**Comment by WilliamTales** [comment]
Hey @norkans7 srr about the delayed response.
Here's a vid showing the CSS error on the editor. thx
https://youtu.be/LXxZdoKcvhk

**Pull request merged**
