### PR TITLE
Improve spanish language

### PR DESCRIPTION
**Pull request by teehamaral**
This PR includes more strings translated in Spanish on Transifex, now with 99%.

### CODE REVIEW

**Comment by teehamaral** [comment]
Can you review?

**Comment by norkans7** [comment]
Please update this to the current latest and we'll merge that

**Comment by norkans7** [comment]
@teehamaral sorry I meant to update the translations to the latest version it seems it was last updated on 2017-09-23 20:13

**Comment by norkans7** [comment]
I updated the Spanish translations in #314

**Pull request closed without merging**
